version: "3.8"

services:
  cldzone:
    image: techakademi/cldzone:2
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cldzone.rule=Host(`www.cldzone.com`)"
        - "traefik.http.routers.cldzone.entrypoints=web"
        - "traefik.http.services.cldzone.loadbalancer.server.port=3000"
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        monitor: 60s
        failure_action: rollback
      rollback_config:
        parallelism: 3
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 40s 
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:3000"]
      start_period: 50s
      interval: 40s
      timeout: 10s
      retries: 3
    logging:
      driver: fluentd
      options:
        tag: cldzone.com
    networks:
      - traefik-vekilnet
      - loglama-lognet


networks:
  traefik-vekilnet:
    external: true
  loglama-lognet:
    external: true