version: '3'
services:
  azure-vote-back:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    logging:
      driver: fluentd
      options:
        tag: techakademivote-redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    networks:
      - vote-net
      - loglama-lognet

  azure-vote-front:
    image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
    environment:
      REDIS: azure-vote-back
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.techakademivote.rule=Host(`www.techakademivote.com`)"
        - "traefik.http.routers.techakademivote.entrypoints=web"
        - "traefik.http.services.techakademivote.loadbalancer.server.port=80"
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 40s 
    logging:
      driver: fluentd
      options:
        tag: techakademivote.com
    networks:
      - vote-net
      - loglama-lognet
      - traefik-vekilnet

networks:
  vote-net:
    external: true
  loglama-lognet:
    external: true
  traefik-vekilnet:
    external: true